export const banks:string[] = [
  'Banco BTG',
  'Banco C6',
  'Banco Daycoval',
  'Cresol',
  'EFÍ Bank',
  'Grafeno',
  'Itaú',
  'LetsBank',
  'Mercado Pago',
  'Nubank',
  'Omie',
  'PagSeguro',
  'Quality',
  'Sicoob',
  'Sicredi',
  'Stone',
  'Unicred',
  'Uniprime',
  'Banco do Brasil',
  'Banco do Nordeste',
  'Banco da Amazônia',
  'Banco do Estado do Espiríto Santo',
  'Banco do Estado do Pará',
  'Banco do Estado do Sergipe',
  'Banco Triângulo',
  'Bank of America',
  'Banrisul',
  'Bradesco',
  'Caixa Econômica Federal',
  'Cora',
  'Credisis',
  'ABC Brasil',
  'Asaas',
  'Banco Original',
  'Banco Safra',
  'Santander',
  'Sofisa',
  'Topazio',
  'BRB',
  'Banco Inter',
  'Next',
  'Iti',
  'Wil Bank',
  'Agi Bank',
  'XP Investimentos',
  'ModalMais',
  'BTG Pactual Digital',
  'Banco Pan',
  'Banco Neon',
  'Banco Mercantil do Brasil',
  'Banestes',
  'BMG',
  'Banco Votorantim',
  'Banco Pine',
  'Banco Rendimento',
  'Banco Luso Brasileiro',
  'CitiBank',
  'Banco Alfa',
  'Banco Western Union',
  'Banco Bocom BBM',
  'Banco J.P. Morgan',
  'Banco Toyota do Brasil',
  'Banco Volvo',
  'Banco Volkswagen',
  'Banco Honda',
  'Banco GMAC',
  'Banco Fator',
  'Banco Fibra',
  'Banco Sofisa Direto',
];
